encoder:
  outdir: './tmp/Single/MountainCarContinuous/AE_7_5_2/'
  context_dataset: './database/MountainCarContinuous/final.npy'
  model: ContextAE
  input_dim: 10
  latent_dim: 2
  hidden_dim: [7,5]
  epochs: 100
  val_epochs: 10
  split: 0.8
  M_N: 0.005
  rate: 0.029983722471931533
  batch: 66
  kfolds: 5

  

  